services:
  
  pgdatabase:

    image: postgres:13

    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=airBnB_DWH

    volumes:
      - /home/ataa/Media/projects/AirBnB-Barcelona-s-Data-Analysis/AirBNB_data/:/var/lib/postgresql/data:rw"
  
    ports:
      - "5432:5432" 
    
    networks:
      - pg_network
    
  pgadmin:

    image: dpage/pgadmin4

    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      
    ports:
      - 80:80

    networks:
      - pg_network

  jupyter_notebook:

    build: 

      context: .
      dockerfile: Dockerfile

    volumes:
      - /home/ataa/Media/projects/AirBnB-Barcelona-s-Data-Analysis/Data:/home/jovyan/Data
      - /home/ataa/Media/projects/AirBnB-Barcelona-s-Data-Analysis/notebooks:/home/jovyan/notebooks  

    ports:
      - "8888:8888"

    networks:
      - pg_network


networks:
  pg_network:
     